# Generated by Django 4.0.2 on 2022-06-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='photos/%y')),
                ('roll_no', models.IntegerField()),
                ('captured_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='unknown/%y')),
            ],
        ),
        migrations.CreateModel(
            name='PersonVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_onn', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
