# Generated by Django 4.0.2 on 2022-05-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_userdata_captured_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='register_on',
            new_name='captured_on',
        ),
        migrations.AddField(
            model_name='personvisit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
