# Generated by Django 4.0.2 on 2022-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_personvisit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvisit',
            name='captured_on',
            field=models.DateTimeField(),
        ),
    ]
