# Generated by Django 4.0.2 on 2022-05-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_personvisit_captured_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personvisit',
            old_name='captured_on',
            new_name='captured_onn',
        ),
    ]
