# Generated by Django 4.0.2 on 2022-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_captured_on_personvisit_captured_onn'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roll_no',
            field=models.ImageField(default=None, max_length=15, upload_to=''),
        ),
    ]
