# Generated by Django 4.0.2 on 2022-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_person_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
