# Generated by Django 4.0.2 on 2022-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_person_image_alter_person_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='photos/%y'),
        ),
    ]
