# Generated by Django 4.0.2 on 2022-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='unknown/%y')),
            ],
        ),
    ]
